# 配置服务访问端口
server:
  port: 8002

# 配置数据库连接和应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: root
  application:
    name: shop_service_user
  # consul配置
  cloud:
    consul:
      # 配置访问consulServer的访问地址
      host: localhost
      # 配置端口
      port: 8500
      # 服务注册与发现的配置
      discovery:
        # 是否注册
        register: true
        # 实例id
        instance-id: ${spring.application.name}:${server.port}
        # 服务实例名称
        service-name: ${spring.application.name}
        # 服务实例端口
        port: ${server.port}
        # 健康检查路径
        health-check-path: /actuator/health
        # 健康检查时间间隔
        health-check-interval: 15s
        # 开启IP地址注册
        prefer-ip-address: true
        # 实例的请求ip
        ip-address: ${spring.cloud.client.ip-address}

# 配置mybatis扫描对象
mybatis:
  mapper-locations: mapper/*.xml


