# 配置服务访问端口
server:
  port: 8001
# 配置数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: root
  application:
    name: shop_service_order

# 配置mybatis扫描对象
mybatis:
  mapper-locations: mapper/*.xml

# 添加Eureka Server的主机地址
eureka:
  client:
    # eureka server的访问路径
    service-url:
      # 8003为eureka的服务端口号
      defaultZone: http://localhost:8003/eureka/,http://localhost:8004/eureka/
  instance:
    # 使用ip进行注册
    prefer-ip-address: true