# 配置服务访问端口
server:
  port: 8002

# 配置数据库连接和应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: root
  application:
    name: shop_service_user

# 配置mybatis扫描对象
mybatis:
  mapper-locations: mapper/*.xml

# 添加Eureka Server的主机地址
eureka:
  client:
    # eureka server的访问地址
    service-url:
      # 8003为eureka server的服务端口号
      defaultZone: http://localhost:8003/eureka/,http://localhost:8004/eureka/
  instance:
    # 使用ip进行注册
    prefer-ip-address: true
    # 发送心跳续约间隔，以便快速注册
    lease-renewal-interval-in-seconds: 5
    # eureka client发送心跳给server端后，续约到期时间（默认90s）
    lease-expiration-duration-in-seconds: 10
    # 配置服务ip地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}