# 搭建高可用的Eureka Server集群
# Eureka1:8003
# Eureka2:8004

# 1、指定引用名称
spring:
  application:
    name: show_eureka_serer


# 配置服务访问端口
server:
  port: 8003


# eureka服务器端控制
eureka:
#  instance:
#    hostname: localhost
  instance:
    hostname: localhost
  client:
    # registerWithEureka: 是否将自己注册到Eureka服务中，本身就是所有无需注册
    # fetchRegistry : 是否从Eureka中获取注册信息
    # serviceUrl: 客户端与Eureka服务端进行交互的地址
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8004/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 剔除无效节点时间间隔
    eviction-interval-timer-in-ms: 4000
    # 自我保护机制等待时间
    #    wait-time-in-ms-when-sync-empty: 4000




