# 配置服务访问端口
server:
  port: 8003

# eureka服务器端控制
eureka:
  instance:
    hostname: 192.168.56.1
    prefer-ip-address: true
  client:
    # registerWithEureka: 是否将自己注册到Eureka服务中，本身就是所有无需注册
    register-with-eureka: false
    # fetchRegistry : 是否从Eureka中获取注册信息
    fetch-registry: false
    # serviceUrl: 客户端与Eureka服务端进行交互的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


